name: Feature Checking

on:
  push:
    branches:
      - 'master'

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  checking-features:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: set up nodejs v18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: install dependencies
        run: yarn install

      - name: start application
        run: yarn start&

      - name: test if app is working
        run: until curl -v http://localhost:3000 > /dev/null; do sleep 1; done
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - name: Install Vercel CLI
        run: yarn global add vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}